@startuml

left to right direction

object User {

}

object Discussion {

}

object Post {

}

object Like {

}

Discussion "1" -- "*" Post
Post "1" -- "*" Like
User "1" -- "*" Like
User "1" -- "*" Discussion
User "1" -- "*" Post

@enduml